import '../../globals.css';
import '../../styles/Home.css';

export const metadata = {
  title: 'Return Policy | Navratna Jewellers',
  description: 'Generated by create next app',
};

export default function ReturnPolicyLayout({ children }) {
  return <div>{children}</div>;
}
