// import '../../globals.css';
// import '../../styles/Home.css';
import 'bootstrap/dist/css/bootstrap.min.css';

export const metadata = {
  title: 'Product | Navratna Jewellers',
  description: 'Generated by create next app',
};

export default function ProductLayout({ children }) {
  return <div>{children}</div>;
}
