export const metadata = {
  title: 'Contact Us | Navratna Jewellers',
  description: 'Generated by create next app',
};

export default function ContactLayout({ children }) {
  return <div>{children}</div>;
}
