'use client';

import Footer from '@/app/components/Footer';
import Header from '@/app/components/Header';
import { useWebStatus } from '@/app/context/status.context';
import { useEffect, useState } from 'react';
import { Affix } from 'rsuite';

export default function TermConditionPage() {
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  // check the website update status
  const { isWebsiteOnUpdate } = useWebStatus();

  if (isWebsiteOnUpdate) {
    window.location.replace('/');
  }

  if (!mounted) return null; // Prevent rendering on the server

  return (
    <div>
      <Affix className="fixed-header">
        <div className="header-container margin-t10">
          <Header />
        </div>
      </Affix>
      <div className="margin-t50 padding-lr5 margin-b100">
        <h3 className="main-color textCenter margin-b30">
          Terms And Conditions
        </h3>
        <p>
          This electronic document is the terms and conditions for access to or
          usage of .In Website, is based on the applicable rules and regulations
          in terms of information technology act, 2000 (“it act, 2000”) and in
          accordance with the provisions of rule 3 (1) of the information
          technology (intermediaries guidelines) rules, 2011.
        </p>

        <p>
          This electronic record is generated by a computer system and does not
          require any physical or digital signatures.
        </p>

        <p>
          The domain name www.navratnajewellers.in, including the related mobile
          site and mobile application as well as the portal .Com (hereinafter
          referred to as “platform”) is owned and operated by
        </p>

        <p>
          <strong> NAVRATNA JEWELLERS </strong>
          <strong> </strong>
        </p>

        <p> 677, Mahatma Gandhi Main Rd </p>

        <p>beside Gurudwara, Lower Bazaar, Ranchi</p>

        <p>Jharkhand 834001</p>

        <p>
          Hereinafter, the word ‘user’ shall collectively imply a .In, a buyer,
          and any visitor on the platform, to you refers to terms of use, ‘you’
          and ‘your’ shall relate to any natural or legal person who has agreed
          to become a buyer on the platform by providing registration data while
          registering on the platform using computer systems. The word and the
          terms ‘we’, ‘us’ and ‘our’ shall mean www.navratnajewellers.in
        </p>

        <p>
          By mere use of this platform, you shall be contracting with
          www.navratnajewellers.in, and these terms and conditions including the
          policies constitute your binding obligations to
          www.navratnajewellers.in
        </p>

        <p>
          We reserve the right, at our sole discretion, to change, modify, add,
          or remove portions of the to you at any time. Your continued use of
          the platform following the changes or updates will mean that you
          accept and agree to the revisions. As long as you comply with the to
          you, we grant you a personal, non-exclusive, non-transferable, and
          limited privilege to enter and use the platform.
        </p>

        <p>
          Only persons eligible form a legally binding contracts under indian
          contract act, 1872 are eligible for membership. Incompetent persons
          cannot enter into a contract. As a minor if youwish to use or transact
          on website, such use or transaction may be made by your legal guardian
          or parents on the website. www.navratnajewellers.in reserves the right
          to terminate your membership and / or refuse to provide you with
          access to the website if it is brought to
          www.navratnajewellers.in&apos;s notice or if it is discovered that you
          are incompetent to contract.
        </p>

        <p>
          If you register, you shall be responsible for all activities that
          occur under your display name and password. You agree that if you
          provide any incorrect information of any type, we shall have the right
          to indefinitely suspend or terminate or block access of your
          membership on the website and refuse to provide you with access to the
          website.
        </p>

        <p>You agree that communications is only through electronic media.</p>

        <p>
          navratnajewellers.in provides the products as detailed in the
          specifications listed against each product. Any mismatches with regard
          to the quality, purity as the case may be, shall be brought to the
          immediate attention of www.navratnajewellers.in where there is genuine
          product errors, www.navratnajewellers.in shall take the
          responsibility. However, such a facility is not available when the
          product is not properly and delicately handled by you as required in
          each specific case.
        </p>

        <p>
          Membership is free for buyers through this website
          navratnajewellers.in does not charge any fee for browsing and buying
          on the website. However, www.navratnajewellers.in has a right to
          charge any fee for whole or partial use of the website, if need be.
        </p>

        <p>
          You agree, undertake and confirm that your use of website shall be
          strictly governed by the following binding principles:
        </p>

        <p>
          You shall not host, display, upload, modify, publish, transmit, update
          or share any information which:
        </p>

        <ul>
          <li>
            <p>
              Belongs to another person and to which you does not have any right
              to not allowed by indian law and /or under any acts in india.
            </p>
          </li>
          <li>
            <p>Is misleading in any way</p>
          </li>
        </ul>

        <p>
          You agree not to use any device, software or routine to interfere or
          attempt to interfere with the proper working of the website or any
          transaction being conducted on the website, or with any other
          person&apos;s use of the website.
        </p>

        <p>
          Our current privacy policy is available at / s /privacy policy. If you
          object to your information being transferred or used in this way
          please do not use website.
        </p>

        <p>
          We and our affiliates will share / sell / transfer / license / covey
          some or all of your personal
        </p>

        <p>
          In this website, all the materials and products contain specifications
          as given against each product. All these products require delicate
          handling and any breakages due to any reasons are not at the fault of
          www.navratnajewellers.in only purity in terms of gold and silver will
          be entertained for replacement, if any.
        </p>

        <p>
          While availing any of the payment method/s available on the website,
          we will not be responsible or assume any liability, what so ever in
          respect of any loss or damage rising directly or indirectly to you due
          to:
        </p>

        <p>Lack of authorization for any transaction/s, or</p>

        <ul>
          <li>
            <p>
              Exceeding the preset limit mutually agreed by you and
              between&quot;bank/s&ldquo;, or
            </p>
          </li>
          <li>
            <p>Any payment issues arising out of the transaction, or</p>
          </li>
          <li>
            <p>Decline of transaction for any other reason/s</p>
          </li>
        </ul>

        <p>
          All payments made against the purchases / services on website by you
          shall be compulsorily in indian rupees acceptable in the republic of
          india. Website will not facilitate transaction with respect to any
          other form of currency with respect to the purchases made on website.
        </p>

        <p>
          Before shipping / delivering your order to you,
          www.navratnajewellers.in may request you to provide supporting
          documents (including but not limited to govt. Issued id and address
          proof) to establish the ownership of the payment instrument used by
          you foryour purchase. This is done in the interest of providing a safe
          online shopping environment to our users.
        </p>

        <p>
          You, as a buyer, understand that upon initiating a transaction you are
          entering into a legally binding and enforceable contract with the .In
          To purchase the products and /or services from the
          www.navratnajewellers.in using the payment facility, and you shall pay
          the transaction price through your issuing bank to the
          www.navratnajewellers.in using payment facility.
        </p>

        <p>
          Except for cash on delivery transaction, refund, if any, shall be made
          at the same issuing bank from where transaction price was received.
        </p>

        <p>
          For cash on delivery transactions, refunds, if any, will be made via
          demand draft in favour of the buyer (as per registration details
          provided by the buyer)
        </p>

        <p>
          Refund shall be made in indian rupees only and shall be equivalent to
          the transaction price received in indian rupees.
        </p>

        <p>
          Replacements are done only based on transaction to transaction basis.
          Under no circumstances, money will be refunded.
        </p>

        <p>
          Jurisdiction is only at coimbatore, tamilnadu, india.
          www.navratnajewellers.in we do not warrant that product description or
          other content of this website is accurate, complete, reliable,
          current, or error-free and assumes no liability in this regard.
        </p>

        <p>
          In no event shall www.navratnajewellers.in be liable for any special,
          incidental,indirect or consequential damages of any kind in connection
          with these terms of use, even if user has been informed in advance of
          the possibility of such damages.
        </p>

        <p>
          Please contact usfor any questions or comments (including all
          inquiries unrelated tocopyright infringement) regarding this website
          Grievance officer In accordance with information technology act 2000
          and rules made there under,the name and contact details of the
          grievance officer are provided below:
        </p>

        <p>
          <br />
        </p>

        <p>
          <strong> NAVRATNA JEWELLERS </strong>
          <strong> </strong>
        </p>

        <p> 677, Mahatma Gandhi Main Rd </p>

        <p>beside Gurudwara, Lower Bazaar, Ranchi</p>

        <p>Jharkhand 834001</p>

        <p>Time: mon - sat (11:00 - 21:00)</p>

        <p>
          If www.navratnajewellers.in has suspicion or knowledge, that any of
          its buyers and www.navratnajewellers.in &quot;s are involved in any
          activity that is intended to provide claims or information thatis
          false, misleading or not genuine, then www.navratnajewellers.in may
          while reserving its rights to initiate civil and/or criminal
          proceedings against user may also at its solediscretion suspend,
          block, restrict, cancel the display name of such buyer and
          www.navratnajewellers.in and /or disqualify that user and any related
          users from availing protection through this program.
        </p>

        <p>
          www.navratnajewellers.in reserves its right to initiate civil and / or
          criminal proceedings against user who, files a invalid and / or false
          claims or provides false, incomplete, or misleading information. In
          addition to the legal proceedings as for said,.In May at its sole
          discretion suspend, block, restrict, cancel the display name [and its
          related display names] of such user and / or disqualify that user and
          any related users from availing protection through this program. Any
          person who, knowingly and with intent to injure, defraud or deceive,
          files a fraudulent complaint containing false, incomplete, or
          misleading information may be guilty of a criminal offence and will be
          prosecuted to the fullest extent of the law.
        </p>
      </div>
      <div className="margin-t50">
        <Footer />
      </div>
    </div>
  );
}
