import { Geist, Geist_Mono } from 'next/font/google';
import 'rsuite/dist/rsuite.min.css';
import './globals.css';
// import './styles/Home.css';
import './styles/newHome.css';
import { ServerProvider } from './context/server.context';
import { DeleteAndVersionProvider } from './context/deleteAndVersion.context';
import { StatusProvider } from './context/status.context';
import { PriceProvider } from './context/price.context';
import { MessageProvider } from './context/message.context';
import { AdminProfileProvider } from './context/adminProfile.context';
import { ProfileProvider } from './context/profile.context';
import { ProductProvider } from './context/product.context';
import { CartProvider } from './context/cart.context';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ServerProvider>
          <DeleteAndVersionProvider>
            <StatusProvider>
              <PriceProvider>
                <MessageProvider>
                  <AdminProfileProvider>
                    <ProfileProvider>
                      <ProductProvider>
                        <CartProvider>{children}</CartProvider>
                      </ProductProvider>
                    </ProfileProvider>
                  </AdminProfileProvider>
                </MessageProvider>
              </PriceProvider>
            </StatusProvider>
          </DeleteAndVersionProvider>
        </ServerProvider>
      </body>
    </html>
  );
}
