import '../globals.css';
import '../styles/Home.css';

export const metadata = {
  title: 'Forget Password | Navratna Jewellers',
  description: 'Generated by create next app',
};

export default function ForgetPasswordLayout({ children }) {
  return <div>{children}</div>;
}
